config/routes.rb
Musicatestdb::Application.routes.draw do
  resources :images

  resources :musics

  resources :comments

  resources :users

  root to: 'home#home'
  
  resources :sessions, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base

	before_create :ensure_user_is_premium

	has_many :comments, foreign_key: :author_id, dependent: :destroy
	has_many :images, dependent: :destroy
	has_many :musics, dependent: :destroy

	has_secure_password

	accepts_nested_attributes_for :musics
    accepts_nested_attributes_for :images

    def role?(role)
 		self.role == role
	end

	validates :email, presence: true, uniqueness: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :on => :create
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, :on => :update
	validates :genre, presence: true, :on => :update
	validates :location, presence: true, :on => :update
	validates :rating, presence: true, :on => :update
	validates :images, presence: true, :on => :update



    attr_accessible :description, :genre, :location, :name, :rating, :musics, :images, :image_upload, :music_upload, :images_attributes, :email, :password, :password_confirmation

    private

    def ensure_user_is_premium
    	self.role = 'premium'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource
  skip_before_filter :authenticate, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render "home/home" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= nested_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>

  <h2>Upload Images</h2>
  <%= render 'image_fields', f: f %> 
 


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_image_fields.html.erb
<%= f.fields_for :images do |images_form| %>
	<div class="field">
    <%= images_form.file_field :image_upload %>
    <%= images_form.label :image_upload %>
    <% if @user.images.size > 0 %>
  <%= image_tag @user.images.first.image_upload.thumb %>
  <% end %>
</p>
  </div>
<% end %>
<%= f.link_to_add 'Add Images', :images %>

app/views/users/_music_fields.html.erb
<%= f.fields_for :musics do |musics_form| %>
	<%= musics_form.label :name %>
	<%= musics_form.text_field :name %>
<% end %>
<%= f.link_to_add 'Add Music', :musics %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
    <h1>DJs</h1>

    <% @users.each do |user| %>
        <div class="user">
            <% if user.images.size > 0 %>
                <%= link_to image_tag(user.images.first.image_upload.thumb.url), user %>
                <% end %> 
            <p><%= user.name %></p>
            <p><%= user.rating %></p>
            <%= link_to 'Edit', edit_user_path(user) %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div> 
            <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

    <% if @user.images.size > 0 %>
    <%= image_tag @user.images.first.image_upload.avatar.url %>
    <% end %>

    <h1><%= @user.name %></h1>

    <h4><p>Tracks</p>
    <% @user.musics.each do |music| %>
    <%= link_to music.name, music%><% end %></li> </h4>


    <h4>Description:</h4>
    <%= @user.description %>


    <h4>Genre:</h4>
    <%= @user.genre %>


    <h4>Location:</h4>
    <%= @user.location %>


    <h4>Rating:</h4>
    <%= @user.rating %>


  <div id="demo-1" class="demobox">
  <% if @user and @user.images.size > 0 %>
    <% @user.images[1..-1].each do |image| %>
      <%= image_tag image.image_upload.details.url %>
    <% end %>
  <% end %>
  </div>

  <!-- <li>Tracks: <% @user.musics.each do |music| %>
  <audio controls>
    <source src="<%= music.music_upload %>" type="audio/ogg">
    <source src="<%= music.music_upload %>" type="audio/mpeg">
  <% end %></li>
   -->

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

</div>