config/routes.rb
Musicatestdb::Application.routes.draw do
  resources :images

  resources :musics

  resources :comments

  resources :users

  root to: 'home#home'
  
  resources :sessions, only: [:create, :destroy]

end

app/models/music.rb
class Music < ActiveRecord::Base

	belongs_to :user
	has_many :comments, dependent: :destroy

  attr_accessible :genre, :image_upload, :remove_image_upload, :music_upload, :remove_music_upload, :name, :rating, :user_id, :comments

  mount_uploader :image_upload, MusicImageUploader
  mount_uploader :music_upload, MusicFileUploader


  validates :name, presence: true
  validates :genre, presence: true
  validates :rating, presence: true

  default_scope order('musics.rating DESC')

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  load_and_authorize_resource
  
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musics }
    end
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    @music = Music.find(params[:id])
    @comment = Comment.new(music_id: params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/new
  # GET /musics/new.json
  def new
    @music = Music.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/1/edit
  def edit
    @music = Music.find(params[:id])
  end

  # POST /musics
  # POST /musics.json
  def create
    params[:music][:user_id] = current_user.id
    puts params[:music][:user_id]
    @music = Music.new(params[:music])

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render json: @music, status: :created, location: @music }
      else
        format.html { render action: "new" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musics/1
  # PUT /musics/1.json
  def update
    @music = Music.find(params[:id])

    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music = Music.find(params[:id])
    @music.destroy

    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.file_field :image_upload %>
    <%= f.label :image_upload %>
  </div>
  <div class="field">
    Remove Picture
  <%= f.check_box :remove_image_upload %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.file_field :music_upload %>
    <%= f.label :music_upload %>
  </div>
  <div class="field">
    Remove Tracks
  <%= f.check_box :remove_music_upload %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<div class="container">
  <h1>Tracks</h1>

  <% @musics.each do |music| %>
    <div class="usermusic">
        <% if music.image_upload.details.url %> <ul class="tunes">
          <div class="record_animation">
            <div class="album">
               <%= image_tag music.image_upload.thumb.url %> 
              <span class="vinyl">
                <div></div>
              </span>
              <ul class="actions">
                <li class="play-pause"><a href="<%= music.music_upload %>"></a></li>
                <li class="info"><%= link_to '', music %></li>
              </ul>
              <span class="gloss"></span>
            </div>
          </div>
        </ul> 
        <% end %>
        <p><%= music.user.name %></p>
        <p><%= music.name %></p>
        <p><%= music.genre %></p>
        <p><%= music.rating %></p>
        <p><%= link_to 'Edit', edit_music_path(music) %></p>
        <p><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>    
  <% end %>

  <div class="btn2">
  <%= link_to image_tag('upload.png'), new_music_path%>
  </div>
</div>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<div class="container">

  <% if @music.image_upload.details.url %>
    <%= image_tag @music.image_upload.details.url %>
    <% end %>

  <p id="notice"><%= notice %></p>

 
    <h4>User</h4>
    <%= @music.user.name %>
  
    <h4>Name</h4>
    <%= @music.name %>
   
    <h4>Genre</h4>
    <%= @music.genre %>
  
    <h4>Rating</h4>
    <%= @music.rating %>
  


   <!--  <% if @music.music_upload %>
    <%= link_to @music.name, @music.music_upload.url %>
    <% end %> -->

    <h4>Music upload:</h4>
    <audio controls>
    <source src="<%= @music.music_upload %>" type="audio/ogg">
    <source src="<%= @music.music_upload %>" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>
    <% if current_user%>
    <a href="<%= @music.music_upload %>">Download audio </a>
    <% else %>
    Please pay
    <% end %>
 
    <h4>Comments</h4>
    
    <% @music.comments.each do |comments| %>
      <p><strong><%= comments.author.name %></strong> <br> <%= comments.date %> <br> "<%= comments.description %>"</p>
    <% end %>
  

  <%= form_for @comment do |f| %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.hidden_field :music_id, value: @music.id %>
    <%= f.submit %>

  <% end %>


  <%= link_to 'Edit', edit_music_path(@music) %> |
  <%= link_to 'Back', musics_path %>

</div>